# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: It's never too late to do the right things!
subtitle: slower is faster!
description: life is never static
keywords: blog, May天, Ran
author: May天
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
    enable: true # Open external links in new tab
    field: site # Apply to the whole site
    exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
    enable: true
    line_number: true
    auto_detect: false
    tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
    path: ''
    per_page: 10
    order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
    -
        type: git
        repo:
            github: git@github.com:Ran-oops/Ran-oops.github.io.git,master
            
    -
        type: baidu_url_submitter

# ---------------------------------------------------------------
# The following is my custom configuration.
# ---------------------------------------------------------------

# site map(google and baidu)
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml

# baidu
baidu_url_submit:
    count: 1000                 # 提交最新的count个链接
    host: blog.caoyu.info       # 在百度站长平台中注册的域名
    token: LNG10P5iQH0yZDxC     # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
    path: baidu_urls.txt        # 文本文档的地址， 新链接会保存在此文本文档里

# cute girl
live2d:
    enable: false
    scriptFrom: local
    pluginRootPath: live2dw/
    pluginJsPath: lib/
    pluginModelPath: assets/
    tagMode: false
    debug: false
    model:
        #    use: live2d-widget-model-z16
        use: live2d-widget-model-koharu
    display:
        position: right
        width: 150
        height: 300
    mobile:
        show: true

# google pwa
# https://github.com/lavas-project/hexo-pwa
pwa:
    manifest:
        path: /pwa.webmanifest
        body:
            name: May天
            short_name: May天
            description: May天's blog
            icons:
                -
                    src: /images/favicon.png
                    sizes: 192x192
                    type: image/png
                -
                    src: /images/favicon.png
                    sizes: 512x512
                    type: image/png
            start_url: /
            theme_color: '#2196f3'
            background_color: '#2196f3'
            display: standalone
    serviceWorker:
        path: /sw.js
        preload:
            urls:
                - /
            posts: 5
        opts:
            networkTimeoutSeconds: 5
        routes:
            -
                pattern: !!js/regexp /hm.baidu.com/
                strategy: networkOnly
            -
                pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
                strategy: cacheFirst
            -
                pattern: !!js/regexp /\//
                strategy: networkFirst
    priority: 5

# Next Theme Local Search
search:
    path: search.xml
    field: post
    format: html
    limit: 10000